import {
  RiTerminalBoxLine,
  RiFocus3Line,
  RiSearch2Line,
  RiBookOpenLine,
  RiBookOpenFill,
  RiRefreshLine,
  RiBookReadLine,
  RiGitRepositoryLine,
  RiCodeSSlashLine,
  RiFileTextLine,
  RiCompass3Line,
  RiSparkling2Line,
  RiSparkling2Fill,
  RiExternalLinkLine,
  RiBook3Line,
  RiCheckboxCircleLine,
  RiFocus3Fill,
  RiSearch2Fill,
  RiHome5Line,
  RiHome5Fill,
  RiBookmarkLine,
  RiBookmarkFill,
  RiArrowRightUpLine,
  RiInformationLine,
  RiTerminalWindowLine,
} from "@remixicon/react";

export const icons = {
  // Semantic Icons Map
  startCoding: RiTerminalBoxLine,
  shortlist: RiFocus3Line,
  shortlistActive: RiFocus3Fill,
  archive: RiSearch2Line,
  archiveActive: RiSearch2Fill,
  library: RiBookmarkLine,
  libraryActive: RiBookmarkFill,
  shuffle: RiRefreshLine,
  read: RiBookReadLine,
  build: RiGitRepositoryLine,
  practice: RiCodeSSlashLine,
  reference: RiFileTextLine,
  surprise: RiCompass3Line,
  search: RiSearch2Line,
  ai: RiSparkling2Line,
  aiActive: RiSparkling2Fill,
  copy: RiSparkling2Line,
  external: RiExternalLinkLine,
  github: RiGitRepositoryLine,
  book: RiBook3Line,
  docs: RiFileTextLine,
  completed: RiCheckboxCircleLine,
  home: RiHome5Line,
  homeActive: RiHome5Fill,
  arrowUpRight: RiArrowRightUpLine,
  info: RiInformationLine,
  terminal: RiTerminalWindowLine,
};
