import { absoluteSiteUrl, SITE_URL } from "../config/site";

export interface LlmsManifest {
  generatedAt: string;
  total: number;
  languages: {
    en: number;
    zh: number;
  };
  sourceRepo: string;
  topCategories: Array<{
    name: string;
    count: number;
  }>;
  paths: number;
  weeklyPick: { weekOf: string } | null;
}

export interface LlmsCollection {
  id: string;
  label: string;
  count: number;
}

export interface GeneratedLlmsFiles {
  summary: string;
  full: string;
}

function markdownLink(label: string, pathname: string): string {
  return `[${label}](${absoluteSiteUrl(pathname)})`;
}

/**
 * Produces the two public AI entry points from pipeline facts only. Personal
 * opinions, individual resource summaries, and review history stay out of
 * these global files unless they exist in the canonical catalog itself.
 */
export function buildLlmsFiles(
  manifest: LlmsManifest,
  collections: LlmsCollection[],
): GeneratedLlmsFiles {
  const generatedAt = new Date(manifest.generatedAt).toISOString();
  const collectionLines = collections.map(
    (collection) => `- **${collection.label}**: ${collection.count.toLocaleString()} items`,
  );
  const categoryLines = manifest.topCategories.map(
    (category) => `- ${category.name}: ${category.count.toLocaleString()} items`,
  );
  const weeklyPickLine = manifest.weeklyPick
    ? `- Current weekly pick data: ${manifest.weeklyPick.weekOf}`
    : "- No current weekly pick is published.";

  const sharedHeader = [
    "# PostSoma DevLibrary",
    "",
    `Canonical site: ${SITE_URL}`,
    `Catalog generated: ${generatedAt}`,
    "",
  ];

  const summary = [
    ...sharedHeader,
    "PostSoma DevLibrary is a bilingual, static archive of free programming learning resources and personally curated open-source references.",
    "",
    "## Start here",
    "",
    `- ${markdownLink("Home", "/")}`,
    `- ${markdownLink("Browse the resource archive", "/resources")}`,
    `- ${markdownLink("Explainable shortlist recommendations", "/recommend")}`,
    `- [Machine-readable catalog](${absoluteSiteUrl("/data/resources.json")})`,
    `- [XML sitemap](${absoluteSiteUrl("/sitemap.xml")})`,
    `- [Full catalog reference](${absoluteSiteUrl("/llms-full.txt")})`,
    "",
    "## Catalog facts",
    "",
    `- Total resources: ${manifest.total.toLocaleString()}`,
    `- English resources: ${manifest.languages.en.toLocaleString()}`,
    `- Chinese resources: ${manifest.languages.zh.toLocaleString()}`,
    ...collectionLines,
    "",
    "## Recommendation policy",
    "",
    "- Recommendations are derived from the published catalog; they must not introduce external resources as if they were catalog entries.",
    "- The catalog records source links and structured metadata. Personal GitHub notes and review dates are only present when explicitly curated.",
    "",
    "This file is generated by the local content pipeline. Do not edit it manually.",
    "",
  ].join("\n");

  const full = [
    ...sharedHeader,
    "This reference map describes the current static catalog. For individual entries, use the machine-readable catalog rather than inferring missing details.",
    "",
    "## Primary entry points",
    "",
    `- ${markdownLink("Home", "/")}`,
    `- ${markdownLink("Resource archive", "/resources")}`,
    `- ${markdownLink("Shortlist recommendations", "/recommend")}`,
    `- [Catalog JSON](${absoluteSiteUrl("/data/resources.json")})`,
    `- [GitHub favorites JSON](${absoluteSiteUrl("/data/github-favorites.json")})`,
    `- [Sitemap](${absoluteSiteUrl("/sitemap.xml")})`,
    "",
    "## Collections",
    "",
    ...collectionLines,
    "",
    "## Language coverage",
    "",
    `- English: ${manifest.languages.en.toLocaleString()} items`,
    `- Chinese: ${manifest.languages.zh.toLocaleString()} items`,
    "",
    "## Largest catalog categories",
    "",
    ...categoryLines,
    "",
    "## Published curation data",
    "",
    `- Learning paths: ${manifest.paths}`,
    weeklyPickLine,
    "- GitHub health indicates the last objective repository check when available; an unchecked item is not a verified maintenance claim.",
    "",
    "## Provenance",
    "",
    `- Upstream programming-resource source: ${manifest.sourceRepo}`,
    "- GitHub favorites are maintained locally with separate human curation and health-check data.",
    "",
    "This file is generated by the local content pipeline. Do not edit it manually.",
    "",
  ].join("\n");

  return { summary, full };
}
